post http://localhost:3003/api/blogs
Content-Type: application/json

{
	"title": "Lorem ipsum",
    "author": "John Doe",
    "url": "https://www.youtube.com",
    "likes": 99,
    "userId": "5d20daed4ef7f01ee4f98ccb"
}